[package]
name = "hide_thread_from_debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { workspace = true, features = [
    "Win32_System_Threading",
    "Wdk_System_Threading",
] }